### ISSUE TITLE
Import Post from GitHub assumes master branch

### ISSUE THREAD

**Issue by slopp** [rstudio/distill#215]
Importing from GitHub fails because it looks up the raw user content assuming a `master` branch.  This means new repos that use the `main` default can not house articles for import. I believe this is caused here:

https://github.com/rstudio/distill/blob/master/R/import.R#L366

The failure scenario looks like this:

```
import_post("https://github.com/user/distill-standalone-post")
Error in open.connection(con, "rb") : HTTP error 404.
```

**Comment by jjallaire** [comment]
Looks like we could call this endpoint to determine the default branch: https://stackoverflow.com/questions/33669534/get-the-repository-default-branch-of-a-github-repository

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/distill/commit/db8c1cfae85e8a2a9c7311474439e7d22dfed28e

**Comment by cderv** [comment]
I think it was still an issue https://community.rstudio.com/t/issues-with-distill-import-post-404-error/91382
I pushed a fix in a PR and tested the example in the community post.

**Comment by jjallaire** [comment]
Thank you!!!
