### ISSUE TITLE
Â before UTF-8 characters, only in posts

### ISSUE THREAD

**Issue by sidvenu** [rstudio/distill#98]
I have 

```
&copy; Copyright 2019 [The Symphony of Statistics](./index.html)

By using this website, you consent to the collection of your personal data in accordance with our [privacy policy](./privacy-policy.html)
```
as my `_footer.html`, formatted as UTF-8 Unicode (with BOM) text.

The copyright symbol shows up properly `©` in `index.html` and `about.html`, but it shows up as `Â©` in posts.

**Comment by gangstR** [comment]
Hmmm... I just ran into this as well.   Yes, it only happens in the posts.  I'm using the latest version of the package with pandoc v2.11.0.4.  I suspect an encoding issue somewhere in the ingestion of the `_footer.html` and the post's associated `.Rmd` file, but I have not had time today to dig through the package and associated scripts to identify where.  In the interim and for the sake of others that might encounter this issue and be just as insistent as I am today on showing the © symbol (versus (c), etc.), then you can use a variation of this horrifically over-engineered solution to get around it.  I don't recommend this, but we do what we do ;-)
 
```
# patch for distill package issue:  https://github.com/rstudio/distill/issues/98

# pardon the verbosity here, but let's help any new R users (yay!)

library(rvest)
library(xml2)

# example you can extend easily to all your posts via a build script...
post.file <- "_site/posts/welcome/index.html"

# read in the post
curr.page <- xml2::read_html(post.file)

# find the footer section
page.footer <- curr.page %>%
  rvest::html_nodes(xpath = "//div[@class='distill-site-nav distill-site-footer']")

# zap the offending char
patched.page.footer <- gsub(pattern = "Â", replacement = "", x = page.footer)

# rewrite the page with the update
new.page <- as.character(curr.page)
new.page <- gsub(page.footer, patched.page.footer, x = new.page, fixed=TRUE)
new.page <- xml2::read_html(new.page)
xml2::write_html(new.page, file = post.file)
```

**Comment by cderv** [comment]
Thanks for the report. 
Can you share a `sessionInfo()` with us also ? Thank you.

**Comment by gangstR** [comment]
Thank you.  Yes, here's my session information:

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] distill_1.1.2 rvest_0.3.5   xml2_1.3.2   

loaded via a namespace (and not attached):
 [1] digest_0.6.25   R6_2.4.1        magrittr_1.5    evaluate_0.14   httr_1.4.2      rlang_0.4.7     rstudioapi_0.11 rmarkdown_2.5   tools_3.6.3    
[10] xfun_0.19       yaml_2.2.1      compiler_3.6.3  htmltools_0.5.0 knitr_1.29      downlit_0.2.0  
```

**Comment by cderv** [comment]
I can reproduce this when I try on Windows. It seems a Windows related issue as I can't reproduce on RStudio Cloud. Looking into it.

**Comment by cderv** [comment]
I think this comes from 
https://github.com/rstudio/distill/blob/cc20d87099b1f4c074884f0c07158367a50076ed/R/utils.R#L191-L193

which is called in `navigation_after_body_html()`

`readChar` does not seem to correctly import the copyright character, at least on Windows when the input file is UTF8. Here what I believe happens in distill: 

``` r
# recreate what happens in Pandoc
test_file <- tempfile(fileext = ".html")
xfun::write_utf8(" &copy; Copyright", test_file)
out_file <- tempfile(fileext = ".html")
# Pandoc will convert HTML &copy; to unicode
rmarkdown::pandoc_convert(test_file, 
                          to = "html", from = "markdown_strict",
                          output = out_file)
# File is UTF8 here, so ok when read as UTF8
xfun::read_utf8(out_file)
#> [1] "<p>© Copyright</p>"

# It seems readChar uses default system encoding
res <- readChar(out_file, nchars = file.info(out_file)$size, useBytes = TRUE)
res
#> [1] "<p>Â© Copyright</p>\r\n"
Encoding(res)
#> [1] "unknown"
# tell R it is UTF-8
Encoding(res) <- "UTF-8"
res
#> [1] "<p>© Copyright</p>\r\n"
```

So I believe this is again an encoding issue on Windows. But @jjallaire I am not sure to understand why this does not happens with `ìndex.Rmd` or `about.Rmd`. How the footer is differently incorporated in those ? 
Can you share some lights on this with me ? 
In the resulting html files, the copyright sign is correctly inserted with correct character.

Also **knitr** and **rmarkdown** [now assumes](https://yihui.org/en/2018/11/biggest-regret-knitr/) everything is UTF8, maybe **distill** can do the same ? 

Note: The conversion for `_footer.html` uses `markdown_strict` without extension. This could be why the `&copy;` is converted. For this specific case where the html valid `&copy;` is not kept by Pandoc, using in the pandoc conversion `+raw_attribute` and `"`&copy;`{=html} Copyright"` in the file would correctly kept `&copy;` in the resulting html file.

**Comment by jjallaire** [comment]
I have no issue w/ also requiring UTF-8 on windows. PR with this change here: https://github.com/rstudio/distill/pull/291

**Comment by cderv** [comment]
This should now be fixed in dev version. Please reopen if it is not. Thank you for the report @sidvenu !

**Comment by ko-suta** [comment]
The issue persists in Linux (Fedora) system for the version 1.3.1. I've been able to solve it by adding `<meta charset="utf-8">`  to the `_footer.html` as suggested [here](https://github.com/jgm/pandoc/issues/3234#issuecomment-260710406).

**Comment by cderv** [comment]
@ko-suta **distill** already have the correct header in its template
https://github.com/rstudio/distill/blob/9bb1e019400de5f0685a43493e11ef077974a54b/inst/rmarkdown/templates/distill_article/resources/default.html#L6

and `_footer.html` is a file provided in a user project as a partial. It will be rendered using Pandoc to be included in a template
* Partial template: https://github.com/rstudio/distill/blob/main/inst/rmarkdown/templates/distill_article/resources/footer.html
* footer example : https://github.com/rstudio/distill/blob/main/docs/_footer.html 

Partial does not have head tag included, and `_footer.html` can be written in markdown

Not sure where `<meta charset="utf-8">` is missing. Please feel free to open a PR where you think it should be added. Thanks !
